# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etf_http_ref.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='etf_http_ref.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x65tf_http_ref.proto\x1a google/protobuf/descriptor.proto\"\xa5\x01\n\x0c\x65tf_http_ref\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12\x0f\n\x07openint\x18\x07 \x01(\x03:.\xd8\xed\x1a\x02\xe2\xed\x1a&https://en.wikipedia.org/wiki/ISO_8601*\xae\x01\n\nTermSource\x12\x1b\n\x17TERM_SOURCE_UNSPECIFIED\x10\x00\x12\x13\n\x0fTERM_SOURCE_ONE\x10\x01\x12\x14\n\x10TERM_SOURCE_FIBO\x10\x02\x12\x13\n\x0fTERM_SOURCE_ISO\x10\x03\x12\x18\n\x14TERM_SOURCE_ISO20022\x10\x04\x12\x13\n\x0fTERM_SOURCE_FIX\x10\x05\x12\x14\n\x10TERM_SOURCE_FPML\x10\x06:8\n\rcoding_scheme\x12\x1f.google.protobuf.MessageOptions\x18\xda\xad\x03 \x01(\t:C\n\x0bterm_source\x12\x1f.google.protobuf.MessageOptions\x18\xdb\xad\x03 \x01(\x0e\x32\x0b.TermSource::\n\x0fterm_source_ref\x12\x1f.google.protobuf.MessageOptions\x18\xdc\xad\x03 \x01(\t:8\n\rmsg_term_link\x12\x1f.google.protobuf.MessageOptions\x18\xdd\xad\x03 \x01(\t:6\n\ris_identifier\x12\x1d.google.protobuf.FieldOptions\x18\xc2\xb5\x03 \x01(\x08:8\n\x0f\x65xternal_schema\x12\x1d.google.protobuf.FieldOptions\x18\xc3\xb5\x03 \x01(\t:8\n\x0f\x66ield_term_link\x12\x1d.google.protobuf.FieldOptions\x18\xc4\xb5\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_TERMSOURCE = _descriptor.EnumDescriptor(
  name='TermSource',
  full_name='TermSource',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_ONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_FIBO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_ISO', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_ISO20022', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_FIX', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERM_SOURCE_FPML', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=225,
  serialized_end=399,
)
_sym_db.RegisterEnumDescriptor(_TERMSOURCE)

TermSource = enum_type_wrapper.EnumTypeWrapper(_TERMSOURCE)
TERM_SOURCE_UNSPECIFIED = 0
TERM_SOURCE_ONE = 1
TERM_SOURCE_FIBO = 2
TERM_SOURCE_ISO = 3
TERM_SOURCE_ISO20022 = 4
TERM_SOURCE_FIX = 5
TERM_SOURCE_FPML = 6

CODING_SCHEME_FIELD_NUMBER = 55002
coding_scheme = _descriptor.FieldDescriptor(
  name='coding_scheme', full_name='coding_scheme', index=0,
  number=55002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
TERM_SOURCE_FIELD_NUMBER = 55003
term_source = _descriptor.FieldDescriptor(
  name='term_source', full_name='term_source', index=1,
  number=55003, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
TERM_SOURCE_REF_FIELD_NUMBER = 55004
term_source_ref = _descriptor.FieldDescriptor(
  name='term_source_ref', full_name='term_source_ref', index=2,
  number=55004, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
MSG_TERM_LINK_FIELD_NUMBER = 55005
msg_term_link = _descriptor.FieldDescriptor(
  name='msg_term_link', full_name='msg_term_link', index=3,
  number=55005, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
IS_IDENTIFIER_FIELD_NUMBER = 56002
is_identifier = _descriptor.FieldDescriptor(
  name='is_identifier', full_name='is_identifier', index=4,
  number=56002, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
EXTERNAL_SCHEMA_FIELD_NUMBER = 56003
external_schema = _descriptor.FieldDescriptor(
  name='external_schema', full_name='external_schema', index=5,
  number=56003, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
FIELD_TERM_LINK_FIELD_NUMBER = 56004
field_term_link = _descriptor.FieldDescriptor(
  name='field_term_link', full_name='field_term_link', index=6,
  number=56004, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_ETF_HTTP_REF = _descriptor.Descriptor(
  name='etf_http_ref',
  full_name='etf_http_ref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='etf_http_ref.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='etf_http_ref.open', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='etf_http_ref.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='etf_http_ref.low', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close', full_name='etf_http_ref.close', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='etf_http_ref.volume', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='openint', full_name='etf_http_ref.openint', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\330\355\032\002\342\355\032&https://en.wikipedia.org/wiki/ISO_8601',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['etf_http_ref'] = _ETF_HTTP_REF
DESCRIPTOR.enum_types_by_name['TermSource'] = _TERMSOURCE
DESCRIPTOR.extensions_by_name['coding_scheme'] = coding_scheme
DESCRIPTOR.extensions_by_name['term_source'] = term_source
DESCRIPTOR.extensions_by_name['term_source_ref'] = term_source_ref
DESCRIPTOR.extensions_by_name['msg_term_link'] = msg_term_link
DESCRIPTOR.extensions_by_name['is_identifier'] = is_identifier
DESCRIPTOR.extensions_by_name['external_schema'] = external_schema
DESCRIPTOR.extensions_by_name['field_term_link'] = field_term_link
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

etf_http_ref = _reflection.GeneratedProtocolMessageType('etf_http_ref', (_message.Message,), {
  'DESCRIPTOR' : _ETF_HTTP_REF,
  '__module__' : 'etf_http_ref_pb2'
  # @@protoc_insertion_point(class_scope:etf_http_ref)
  })
_sym_db.RegisterMessage(etf_http_ref)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(coding_scheme)
term_source.enum_type = _TERMSOURCE
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(term_source)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(term_source_ref)
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(msg_term_link)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(is_identifier)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(external_schema)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field_term_link)

_ETF_HTTP_REF._options = None
# @@protoc_insertion_point(module_scope)
